/********************************************************************
* rootio/hplDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootio/hplDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablehplDict();
extern void G__cpp_setup_inheritancehplDict();
extern void G__cpp_setup_typetablehplDict();
extern void G__cpp_setup_memvarhplDict();
extern void G__cpp_setup_globalhplDict();
extern void G__cpp_setup_memfunchplDict();
extern void G__cpp_setup_funchplDict();
extern void G__set_cpp_environmenthplDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "rootio/hpl.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__hplDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__hplDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__hplDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__hplDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__hplDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__hplDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__hplDictLN_TH1;
extern G__linked_taginfo G__hplDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__hplDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__hplDictLN_TMatrixTBaselEdoublegR;

/* STUB derived class for protected member access */
