/********************************************************************
* rootio/JSONDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootio/JSONDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJSONDict();
extern void G__cpp_setup_inheritanceJSONDict();
extern void G__cpp_setup_typetableJSONDict();
extern void G__cpp_setup_memvarJSONDict();
extern void G__cpp_setup_globalJSONDict();
extern void G__cpp_setup_memfuncJSONDict();
extern void G__cpp_setup_funcJSONDict();
extern void G__set_cpp_environmentJSONDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "rootio/JSON.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JSONDictLN_string;
extern G__linked_taginfo G__JSONDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JSONDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JSONDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JSONDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JSONDictLN_pairlEintcOintgR;
extern G__linked_taginfo G__JSONDictLN_JSON;
extern G__linked_taginfo G__JSONDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__JSONDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JSONDictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR;
extern G__linked_taginfo G__JSONDictLN_reverse_iteratorlEvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JSONDictLN_maplEintcOvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__JSONDictLN_maplEintcOvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRsPgRsPgRsPgRcLcLiterator;

/* STUB derived class for protected member access */
