/********************************************************************
* rootio/PidDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootio/PidDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePidDataDict();
extern void G__cpp_setup_inheritancePidDataDict();
extern void G__cpp_setup_typetablePidDataDict();
extern void G__cpp_setup_memvarPidDataDict();
extern void G__cpp_setup_globalPidDataDict();
extern void G__cpp_setup_memfuncPidDataDict();
extern void G__cpp_setup_funcPidDataDict();
extern void G__set_cpp_environmentPidDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "rootio/PidData.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PidDataDictLN_TClass;
extern G__linked_taginfo G__PidDataDictLN_TBuffer;
extern G__linked_taginfo G__PidDataDictLN_TMemberInspector;
extern G__linked_taginfo G__PidDataDictLN_TObject;
extern G__linked_taginfo G__PidDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PidDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PidDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PidDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PidDataDictLN_PidData;

/* STUB derived class for protected member access */
