/********************************************************************
* rootio/PidTableDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootio/PidTableDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePidTableDict();
extern void G__cpp_setup_inheritancePidTableDict();
extern void G__cpp_setup_typetablePidTableDict();
extern void G__cpp_setup_memvarPidTableDict();
extern void G__cpp_setup_globalPidTableDict();
extern void G__cpp_setup_memfuncPidTableDict();
extern void G__cpp_setup_funcPidTableDict();
extern void G__set_cpp_environmentPidTableDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "rootio/PidTable.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PidTableDictLN_TClass;
extern G__linked_taginfo G__PidTableDictLN_TBuffer;
extern G__linked_taginfo G__PidTableDictLN_TDirectory;
extern G__linked_taginfo G__PidTableDictLN_TMemberInspector;
extern G__linked_taginfo G__PidTableDictLN_TObject;
extern G__linked_taginfo G__PidTableDictLN_TString;
extern G__linked_taginfo G__PidTableDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__PidTableDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PidTableDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PidTableDictLN_TList;
extern G__linked_taginfo G__PidTableDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PidTableDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PidTableDictLN_TIter;
extern G__linked_taginfo G__PidTableDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PidTableDictLN_TF1;
extern G__linked_taginfo G__PidTableDictLN_TH1;
extern G__linked_taginfo G__PidTableDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PidTableDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PidTableDictLN_TH1D;
extern G__linked_taginfo G__PidTableDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PidTableDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PidTableDictLN_TH2;
extern G__linked_taginfo G__PidTableDictLN_TH2D;
extern G__linked_taginfo G__PidTableDictLN_PidData;
extern G__linked_taginfo G__PidTableDictLN_PidTable;

/* STUB derived class for protected member access */
