/********************************************************************
* rootio/TAnaMuonDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootio/TAnaMuonDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTAnaMuonDict();
extern void G__cpp_setup_inheritanceTAnaMuonDict();
extern void G__cpp_setup_typetableTAnaMuonDict();
extern void G__cpp_setup_memvarTAnaMuonDict();
extern void G__cpp_setup_globalTAnaMuonDict();
extern void G__cpp_setup_memfuncTAnaMuonDict();
extern void G__cpp_setup_funcTAnaMuonDict();
extern void G__set_cpp_environmentTAnaMuonDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "rootio/TAnaMuon.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TAnaMuonDictLN_TClass;
extern G__linked_taginfo G__TAnaMuonDictLN_TBuffer;
extern G__linked_taginfo G__TAnaMuonDictLN_TMemberInspector;
extern G__linked_taginfo G__TAnaMuonDictLN_TObject;
extern G__linked_taginfo G__TAnaMuonDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TAnaMuonDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAnaMuonDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TAnaMuonDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TAnaMuonDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TAnaMuonDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TAnaMuonDictLN_TVector3;
extern G__linked_taginfo G__TAnaMuonDictLN_TAnaTrack;
extern G__linked_taginfo G__TAnaMuonDictLN_xpTrack;
extern G__linked_taginfo G__TAnaMuonDictLN_TAnaMuon;
extern G__linked_taginfo G__TAnaMuonDictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__TAnaMuonDictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR;

/* STUB derived class for protected member access */
