/********************************************************************
* rootio/TAnaJetDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootio/TAnaJetDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTAnaJetDict();
extern void G__cpp_setup_inheritanceTAnaJetDict();
extern void G__cpp_setup_typetableTAnaJetDict();
extern void G__cpp_setup_memvarTAnaJetDict();
extern void G__cpp_setup_globalTAnaJetDict();
extern void G__cpp_setup_memfuncTAnaJetDict();
extern void G__cpp_setup_funcTAnaJetDict();
extern void G__set_cpp_environmentTAnaJetDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "rootio/TAnaJet.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TAnaJetDictLN_TClass;
extern G__linked_taginfo G__TAnaJetDictLN_TBuffer;
extern G__linked_taginfo G__TAnaJetDictLN_TMemberInspector;
extern G__linked_taginfo G__TAnaJetDictLN_TObject;
extern G__linked_taginfo G__TAnaJetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TAnaJetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAnaJetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TAnaJetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TAnaJetDictLN_TVector3;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TAnaJetDictLN_TAnaVertex;
extern G__linked_taginfo G__TAnaJetDictLN_TAnaJet;

/* STUB derived class for protected member access */
