/********************************************************************
* rootio/TGenCandDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootio/TGenCandDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenCandDict();
extern void G__cpp_setup_inheritanceTGenCandDict();
extern void G__cpp_setup_typetableTGenCandDict();
extern void G__cpp_setup_memvarTGenCandDict();
extern void G__cpp_setup_globalTGenCandDict();
extern void G__cpp_setup_memfuncTGenCandDict();
extern void G__cpp_setup_funcTGenCandDict();
extern void G__set_cpp_environmentTGenCandDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "rootio/TGenCand.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenCandDictLN_TClass;
extern G__linked_taginfo G__TGenCandDictLN_TBuffer;
extern G__linked_taginfo G__TGenCandDictLN_TMemberInspector;
extern G__linked_taginfo G__TGenCandDictLN_TObject;
extern G__linked_taginfo G__TGenCandDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TGenCandDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGenCandDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenCandDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGenCandDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenCandDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenCandDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenCandDictLN_TVector3;
extern G__linked_taginfo G__TGenCandDictLN_TLorentzVector;
extern G__linked_taginfo G__TGenCandDictLN_TGenCand;

/* STUB derived class for protected member access */
