/********************************************************************
* rootio/TSimpleTrackDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootio/TSimpleTrackDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSimpleTrackDict();
extern void G__cpp_setup_inheritanceTSimpleTrackDict();
extern void G__cpp_setup_typetableTSimpleTrackDict();
extern void G__cpp_setup_memvarTSimpleTrackDict();
extern void G__cpp_setup_globalTSimpleTrackDict();
extern void G__cpp_setup_memfuncTSimpleTrackDict();
extern void G__cpp_setup_funcTSimpleTrackDict();
extern void G__set_cpp_environmentTSimpleTrackDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "rootio/TSimpleTrack.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSimpleTrackDictLN_TClass;
extern G__linked_taginfo G__TSimpleTrackDictLN_TBuffer;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMemberInspector;
extern G__linked_taginfo G__TSimpleTrackDictLN_TObject;
extern G__linked_taginfo G__TSimpleTrackDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TSimpleTrackDictLN_TVector3;
extern G__linked_taginfo G__TSimpleTrackDictLN_TSimpleTrack;
extern G__linked_taginfo G__TSimpleTrackDictLN_TSimpleTrackcLcLIDX;
extern G__linked_taginfo G__TSimpleTrackDictLN_TSimpleTrackcLcLBIT;

/* STUB derived class for protected member access */
