/********************************************************************
* rootio/TTrgObjDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootio/TTrgObjDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTrgObjDict();
extern void G__cpp_setup_inheritanceTTrgObjDict();
extern void G__cpp_setup_typetableTTrgObjDict();
extern void G__cpp_setup_memvarTTrgObjDict();
extern void G__cpp_setup_globalTTrgObjDict();
extern void G__cpp_setup_memfuncTTrgObjDict();
extern void G__cpp_setup_funcTTrgObjDict();
extern void G__set_cpp_environmentTTrgObjDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "rootio/TTrgObj.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTrgObjDictLN_TClass;
extern G__linked_taginfo G__TTrgObjDictLN_TBuffer;
extern G__linked_taginfo G__TTrgObjDictLN_TMemberInspector;
extern G__linked_taginfo G__TTrgObjDictLN_TObject;
extern G__linked_taginfo G__TTrgObjDictLN_TString;
extern G__linked_taginfo G__TTrgObjDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TTrgObjDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTrgObjDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTrgObjDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTrgObjDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TTrgObjDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TTrgObjDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TTrgObjDictLN_TLorentzVector;
extern G__linked_taginfo G__TTrgObjDictLN_TTrgObj;

/* STUB derived class for protected member access */
