/********************************************************************
* MuScleFitCorrectorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MuScleFitCorrectorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMuScleFitCorrectorDict();
extern void G__cpp_setup_inheritanceMuScleFitCorrectorDict();
extern void G__cpp_setup_typetableMuScleFitCorrectorDict();
extern void G__cpp_setup_memvarMuScleFitCorrectorDict();
extern void G__cpp_setup_globalMuScleFitCorrectorDict();
extern void G__cpp_setup_memfuncMuScleFitCorrectorDict();
extern void G__cpp_setup_funcMuScleFitCorrectorDict();
extern void G__set_cpp_environmentMuScleFitCorrectorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MuScleFitCorrector.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TString;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_scaleFunctBaselEdoublemUgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_vectorlEParameterSetcOallocatorlEParameterSetgRsPgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_reverse_iteratorlEvectorlEParameterSetcOallocatorlEParameterSetgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_resolFunctBaselEdoublemUgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TLorentzVector;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_TRandom3;
extern G__linked_taginfo G__MuScleFitCorrectorDictLN_MuScleFitCorrector;

/* STUB derived class for protected member access */
