/********************************************************************
* AnalysisCutsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error AnalysisCutsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAnalysisCutsDict();
extern void G__cpp_setup_inheritanceAnalysisCutsDict();
extern void G__cpp_setup_typetableAnalysisCutsDict();
extern void G__cpp_setup_memvarAnalysisCutsDict();
extern void G__cpp_setup_globalAnalysisCutsDict();
extern void G__cpp_setup_memfuncAnalysisCutsDict();
extern void G__cpp_setup_funcAnalysisCutsDict();
extern void G__set_cpp_environmentAnalysisCutsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AnalysisCuts.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AnalysisCutsDictLN_TClass;
extern G__linked_taginfo G__AnalysisCutsDictLN_TBuffer;
extern G__linked_taginfo G__AnalysisCutsDictLN_TMemberInspector;
extern G__linked_taginfo G__AnalysisCutsDictLN_TObject;
extern G__linked_taginfo G__AnalysisCutsDictLN_TString;
extern G__linked_taginfo G__AnalysisCutsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AnalysisCutsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnalysisCutsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AnalysisCutsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AnalysisCutsDictLN_AnalysisCuts;

/* STUB derived class for protected member access */
