/********************************************************************
* initFuncDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error initFuncDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableinitFuncDict();
extern void G__cpp_setup_inheritanceinitFuncDict();
extern void G__cpp_setup_typetableinitFuncDict();
extern void G__cpp_setup_memvarinitFuncDict();
extern void G__cpp_setup_globalinitFuncDict();
extern void G__cpp_setup_memfuncinitFuncDict();
extern void G__cpp_setup_funcinitFuncDict();
extern void G__set_cpp_environmentinitFuncDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "initFunc.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__initFuncDictLN_TClass;
extern G__linked_taginfo G__initFuncDictLN_TBuffer;
extern G__linked_taginfo G__initFuncDictLN_TMemberInspector;
extern G__linked_taginfo G__initFuncDictLN_TObject;
extern G__linked_taginfo G__initFuncDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__initFuncDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__initFuncDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__initFuncDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__initFuncDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__initFuncDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__initFuncDictLN_TF1;
extern G__linked_taginfo G__initFuncDictLN_TH1;
extern G__linked_taginfo G__initFuncDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__initFuncDictLN_initFunc;

/* STUB derived class for protected member access */
